apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mdtahmeed-db
      app.kubernetes.io/component: mdtahmeed-db
      app.kubernetes.io/instance: mdtahmeed-db
    name: mdtahmeed-db
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mdtahmeed-db:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: /DO288-appsGE/apps/deployments-strategy/users-db
      git:
        uri: https://github.com/tomhac3k/DO288
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: mysql-app:DO180
      type: Docker
    triggers:
    - github:
        secret: CFKcy1OB3bssteNY02iW
      type: GitHub
    - generic:
        secret: hnkuJAkSoDu0VWU9A1MM
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mdtahmeed-db
      app.kubernetes.io/component: mdtahmeed-db
      app.kubernetes.io/instance: mdtahmeed-db
    name: mdtahmeed-db
  spec:
    replicas: 1
    selector:
      deploymentconfig: mdtahmeed-db
    strategy:
      type: Recreate
      recreateParams:
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: mdtahmeed-db
            command: ["/post-deploy/import.sh"]
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: mdtahmeed-db
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: lenskart
          - name: MYSQL_PASSWORD
            value: redhat
          - name: MYSQL_USER
            value: mdtahmeed
          image: mdtahmeed-db:latest
          name: mdtahmeed-db
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mdtahmeed-db
        from:
          kind: ImageStreamTag
          name: mdtahmeed-db:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mdtahmeed-db
      app.kubernetes.io/component: mdtahmeed-db
      app.kubernetes.io/instance: mdtahmeed-db
    name: mdtahmeed-db
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deploymentconfig: mdtahmeed-db
  status:
    loadBalancer: {}
kind: List
metadata: {}
