FROM docker.io/redhat/ubi8


RUN yum install httpd -y && yum install httpd-manual -y && yum clean all

USER 1001

COPY index.html /var/www/html/

EXPOSE 8080

ENTRYPOINT ["httpd", "-D", "FOREGROUND"]
