apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: do288
      app.kubernetes.io/component: do288
      app.kubernetes.io/instance: do288
    name: do288
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: do288
      app.kubernetes.io/component: do288
      app.kubernetes.io/instance: do288
    name: do288
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: do288:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: /php
      git:
        uri: https://github.com/tomhac3k/DO288
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:8.0-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: Dn2B96HYVkD4Je7hiD1g
      type: GitHub
    - generic:
        secret: XEjBHsfAgcgnp-VyEdLw
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: do288
      app.kubernetes.io/component: do288
      app.kubernetes.io/instance: do288
    name: do288
  spec:
    replicas: 1
    selector:
      deploymentconfig: do288
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: do288
      spec:
        containers:
        - image: do288:latest
          name: do288
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - do288
        from:
          kind: ImageStreamTag
          name: do288:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: do288
      app.kubernetes.io/component: do288
      app.kubernetes.io/instance: do288
    name: do288
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: do288
  status:
    loadBalancer: {}
kind: List
metadata: {}
