apiVersion: v1
data:
  index.html: |
    Custom index file for Kustomize
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: docroot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: xhttpd
  name: xhttpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xhttpd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xhttpd
    spec:
      containers:
      - image: quay.io/tomhac3k/httpd:DO180
        name: httpd
        volumeMounts:
        - mountPath: /var/www/html
          name: docroot
      volumes:
      - name: docroot
        configMap:
          name: docroot
          
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: xhttpd
  name: xhttpd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: xhttpd
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: xhttpd
  name: xhttpd
spec:
  port:
    targetPort: 8080
  to:
    kind: ""
    name: xhttpd
    weight: null
status: {}
