apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-httpd
      app.kubernetes.io/component: my-httpd
      app.kubernetes.io/instance: my-httpd
    name: httpd
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/tomhac3k/httpd:DO180
      from:
        kind: DockerImage
        name: quay.io/tomhac3k/httpd:DO180
      generation: null
      importPolicy:
        importMode: Legacy
      name: DO180
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-httpd
      app.kubernetes.io/component: my-httpd
      app.kubernetes.io/instance: my-httpd
    name: my-httpd
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-httpd
      app.kubernetes.io/component: my-httpd
      app.kubernetes.io/instance: my-httpd
    name: my-httpd
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: my-httpd:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: /deployment-strategy/
      git:
        uri: https://github.com/tomhac3k/DO288
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: httpd:DO180
      type: Docker
    triggers:
    - github:
        secret: gLf5usOzCA0guaWja5ea
      type: GitHub
    - generic:
        secret: WqiVM5j6GQXN2Gih_0Fq
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-httpd
      app.kubernetes.io/component: my-httpd
      app.kubernetes.io/instance: my-httpd
    name: my-httpd
  spec:
    replicas: 1
    selector:
      deploymentconfig: my-httpd
    straitegy:
      type: Recreate
      recreateParams:
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: my-httpd
            command: ["./test-script.sh"]
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: my-httpd
      spec:
        containers:
        - image: my-httpd:latest
          name: my-httpd
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - my-httpd
        from:
          kind: ImageStreamTag
          name: my-httpd:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-httpd
      app.kubernetes.io/component: my-httpd
      app.kubernetes.io/instance: my-httpd
    name: my-httpd
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: my-httpd
  status:
    loadBalancer: {}
kind: List
metadata: {}
