apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-db
  name: mysql-db
  namespace: deployments-stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      restartPolicy: Always
      containers:
      - image: registry.ocp4.example.com:8443/rhel8/mysql-80
        imagePullPolicy: Always
        name: mysql-80
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_USER
          value: dbuser
        - name: MYSQL_PASSWORD
          value: dbuser
        - name: MYSQL_DATABASE
          value: items
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
